export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"64624544820441001fb0b5c6",
				"64624544820441001fb0b5c2",
				"65fd2210fdcae00021e05ffa",
				"66fbc4b5e778710018d3c4b7"
			]
		},
		"64624544820441001fb0b5c2": {
			"id": "64624544820441001fb0b5c2",
			"name": "Main",
			"pageUrl": "index"
		},
		"64624544820441001fb0b5c6": {
			"id": "64624544820441001fb0b5c6",
			"name": "404",
			"pageUrl": "404",
			"seo": {
				"hide": true
			}
		},
		"65fd2210fdcae00021e05ffa": {
			"pageUrl": "moskovskiy",
			"id": "65fd2210fdcae00021e05ffa",
			"name": "Moskovskiy",
			"seo": {
				"title": "ЖК «Московский» - Современный жилой комплекс комфорт класса ",
				"description": "ЖК «Московский» — это современный\nжилой комплекс комфорт-класса,\nстроящийся в Махачкале\nпо адресу ул. Даганова, 139.",
				"og:description": "ЖК «Московский» — это современный\nжилой комплекс комфорт-класса,\nстроящийся в Махачкале\nпо адресу ул. Даганова, 139.",
				"og:title": "Оазис на берегу моря! Новый ЖК \"Пушкин Resort\". ",
				"favicon_32px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/favicon-32x32.png?v=2025-06-03T09:53:03.204Z",
				"favicon_apple_152px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/apple-icon-152x152.png?v=2025-06-03T09:53:29.370Z",
				"favicon_win10_270px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/ms-icon-310x310.png?v=2025-06-03T09:53:40.471Z",
				"background_win10": "#ff0408"
			}
		},
		"66fbc4b5e778710018d3c4b7": {
			"pageUrl": "zhemchuzhina",
			"seo": {
				"title": "ЖК \"Жемчужина Избербаша\" ",
				"description": "Элитный ЖК на берегу моря. Рассрочка на 3 года. Перспективный район!",
				"og:description": "Элитный ЖК на берегу моря. Рассрочка на 3 года. Перспективный район!",
				"og:title": "ЖК \"Жемчужина Избербаша\" ",
				"favicon_32px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/Pushkin%20Resort%20black.webp?v=2024-03-22T06:52:19.554Z",
				"favicon_apple_152px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/apple-touch-icon.png?v=2024-03-22T08:40:48.411Z",
				"favicon_win10_270px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/android-chrome-512x512.png?v=2024-03-22T08:41:38.675Z",
				"og:image": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/img824.jpg?v=2024-10-01T11:19:29.880Z"
			},
			"id": "66fbc4b5e778710018d3c4b7",
			"name": "Zhemchuzhina"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"title": "Элитный ЖК  \"2 КИТА\" г. Избербаш",
			"description": "Элитный ЖК на берегу моря. Рядом горячие источники, аквапарк, новый детский сад. Рассрочка на 3 года.",
			"background_win10": "#0429ff",
			"favicon_32px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/favicon-32x32.png?v=2023-05-16T06:41:53.296Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/ms-icon-310x310.png?v=2023-05-16T06:42:15.248Z",
			"og:description": "Элитный ЖК на берегу моря. Рядом горячие источники, аквапарк, новый детский сад. Рассрочка на 3 года.",
			"og:title": "Элитный ЖК  \"2 КИТА\" г. Избербаш",
			"og:image": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/1.jpg?v=2024-03-22T06:25:47.898Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/apple-icon-152x152.png?v=2023-05-16T06:42:04.713Z",
			"robotsFileType": "autogenerated",
			"customSitemapDomain": "https://2-kita.ru/",
			"sitemapFileType": "autogenerated"
		}
	}
}