export default {
	"pages": {
		"root": {
			"id": "root",
			"pageUrl": "root",
			"name": "root",
			"children": [
				"64624544820441001fb0b5c6",
				"64624544820441001fb0b5c2"
			]
		},
		"64624544820441001fb0b5c2": {
			"id": "64624544820441001fb0b5c2",
			"name": "Main",
			"pageUrl": "index"
		},
		"64624544820441001fb0b5c6": {
			"id": "64624544820441001fb0b5c6",
			"name": "404",
			"pageUrl": "404"
		}
	},
	"mode": "production",
	"projectType": "gatsby",
	"site": {
		"styles": {},
		"seo": {
			"title": "Элитный ЖК  \"2 КИТА\" г. Избербаш",
			"description": "Элитный ЖК на берегу моря. Рядом горячие источники, аквапарк, новый детский сад. Рассрочка на 3 года.",
			"background_win10": "#0429ff",
			"favicon_32px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/favicon-32x32.png?v=2023-05-16T06:41:53.296Z",
			"favicon_win10_270px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/ms-icon-310x310.png?v=2023-05-16T06:42:15.248Z",
			"og:description": "Элитный ЖК на берегу моря. Рядом горячие источники, аквапарк, новый детский сад. Рассрочка на 3 года.",
			"og:title": "Элитный ЖК  \"2 КИТА\" г. Избербаш",
			"og:image": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/img957.webp?v=2023-05-17T05:35:34.295Z",
			"favicon_apple_152px": "https://uploads.quarkly.io/64624544820441001fb0b59f/images/apple-icon-152x152.png?v=2023-05-16T06:42:04.713Z",
			"robotsFileType": "autogenerated",
			"customSitemapDomain": "https://2-kita.ru/",
			"sitemapFileType": "autogenerated"
		}
	}
}